export const events = [
  {
    _id: 1,
    title: "Neon Nights Festival",
    category: "Music",
    image: "https://images.unsplash.com/photo-1506157786151-b8491531f063",
    location: "Central Park, New York",
    description: "Experience an electrifying night with top DJs.",
    date: { day: "14", month: "APR" },
    price: 120,
    numberOfSeats: 42,
    filter: "Today",
  },
  {
    _id: 2,
    title: "Modern Pottery Workshop",
    category: "Workshop",
    image: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0",
    location: "Studio 42, Brooklyn",
    description: "Learn wheel throwing from expert artists.",
    date: { day: "18", month: "APR" },
    price: 45,
    numberOfSeats: 8,
    filter: "Tomorrow",
  },
  {
    _id: 3,
    title: "Future of AI Summit",
    category: "Tech",
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87",
    location: "Innovation Center, NYC",
    description: "Join leaders discussing AI & ML trends.",
    date: { day: "22", month: "APR" },
    price: 0,
    numberOfSeats: 150,
    filter: "This Weekend",
  },
  {
    _id: 4,
    title: "Startup Networking",
    category: "Business",
    image: "https://images.unsplash.com/photo-1556761175-b413da4baf72",
    location: "Downtown Hub",
    description: "Meet founders and investors.",
    date: { day: "25", month: "APR" },
    price: 30,
    numberOfSeats: 0,
    filter: "Today",
  },
  {
    _id: 5,
    title: "Food Carnival",
    category: "Food",
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836",
    location: "City Square",
    description: "Taste dishes from around the world.",
    date: { day: "27", month: "APR" },
    price: 10,
    numberOfSeats: 65,
    filter: "This Weekend",
  },
  {
    _id: 6,
    title: "Marathon 2026",
    category: "Sports",
    image: "https://images.unsplash.com/photo-1552674605-db6ffd4facb5",
    location: "Riverside Park",
    description: "Run for fitness and fun.",
    date: { day: "29", month: "APR" },
    price: 0,
    numberOfSeats: 200,
    filter: "Tomorrow",
  },
];
